# Generated by Django 4.1.7 on 2023-04-01 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="community",
            options={"verbose_name_plural": "Communities"},
        ),
        migrations.AlterField(
            model_name="community",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True, related_name="subscribed_communities", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
